---
driver:
  name: vagrant
  
provisioner:
  name: chef_solo
  
platforms:
  - name: centos-6.5
  - name: ventos-7.2
  
suites:
  - name: default
    run_list:
      - recipe[acme-trac::default]
    attributes: